### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by eduardosuarez-ntt** [pdxcat/puppet-module-nrpe#48]
Hi,

Would it be possible to release a new version of the module in Puppet Forge?

We are really interested in the changes made in the commit:

https://github.com/pdxcat/puppet-module-nrpe/commit/c7369af02f6ff92c2da698997c391eec1f678739

Thanks you very much in advance.

**Comment by fvanboven** [comment]
Same here, we're currently locked to commit aca063f1e0474b041a32c5f0fbfc4f6094af9134, we would like to move it to the Forge again.

**Comment by squidboylan** [comment]
I just released 2.1.0 on the forge so it should be good to go now, closing this issue
