### ISSUE TITLE
File permissions of released 2.1.0 module

### ISSUE THREAD

**Issue by thlapin** [pdxcat/puppet-module-nrpe#52]
The file permissions of the latest version of the module (2.1.0) are only readable by the owner. (0400). This effect is that if you have a puppetmaster setup where the files are owned by a different user than puppet.

All other modules that I've used from the forge, the files are 0444.

**Comment by squidboylan** [comment]
OK, I just release 2.1.1 which should fix this

**Comment by thlapin** [comment]
Tested and confirmed. Thanks.
